### ISSUE TITLE
[POST]

### ISSUE THREAD

**Issue by Anjonggil** [jo-minjun/my-blog#4]
1. 목차를 열어 해당하는 섹션을 눌러주세요.
2. url을 복사해서 붙여넣어 주세요. e.g. https://jo-minjun.github.io/notes/12-factor-app/#1-codebase
- https://jo-minjun.github.io/doodles/%EB%8C%80%ED%99%94%EB%B2%95/#1-%EC%95%84%EB%8B%88-%EA%B7%BC%EB%8D%B0---%EC%96%B4%EB%95%8C
3. 변경 요청 내용을 작성해주세요.
---
 제가 자주 사용한 이 문장은 상대방 말에 반박을 하면서 내 많이 옳다는 것을 강조합니다. ->  제가 자주 사용한 이 문장은 상대방 말에 반박을 하면서 내 말이 옳다는 것을 강조합니다.

**Comment by jo-minjun** [comment]
오타 수정했습니다.
감사합니다.
